name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - 'master'
    paths-ignore:
      - "**.md"

jobs:
  test:
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: jdxcode/rtx-action@v1
      - name: Test plugin
        run: |
          rtx i ruby
          rtx x ruby -- ruby -v

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        run: shellcheck bin/* lib/*

  format:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install shfmt
        run: brew install shfmt

      - name: Run shfmt
        run: shfmt -i 2 -d bin/ lib/
